### PR TITLE
Amiga port

### PR DESCRIPTION
**Pull request by polluks**
See http://aminet.net/package/util/arc/Deark

### CODE REVIEW

**Comment by jsummers** [comment]
Is the problem here just that lstat() doesn't exist or doesn't work?

I want to work toward making more things configurable by creating local[12].mk files, instead of customizing deark-config.h. I'm not sure about autodetecting this, though (based __INTSIZE??).

**Comment by polluks** [comment]
It's simply not part of http://aminet.net/package/dev/c/vbcc_PosixLib
I see. `__INTSIZE` is just a hack to identify the compiler (there's no official macro).

**Comment by jsummers** [comment]
OK. With the recent changes, I hope it will work if you create a local2.mk file containing "CFLAGS += -DDE_USE_LSTAT=0 -DDE_USE_FSEEKO=0".

At least for now, though, I don't want to try to autodetect it.

**Comment by polluks** [comment]
I see, works. Thanks.
How about additing local1.mk and local2.mk to .gitignore?

**Comment by jsummers** [comment]
I thought about putting local*.mk in .gitignore, but decided it would be too easy for me to mess something up, if forget that I was using/testing them. Users who want to can exclude them locally in .git/info/exclude.

**Pull request closed without merging**
